#!/usr/bin/env bash
# Install udev rules for USB device access without sudo.
# Covers Samsung (Heimdall), Android (ADB/fastboot), STM32 (ST-Link),
# ESP32, Arduino, and other OSmosis-supported devices.
#
# Called by `make install`. Safe to run multiple times.
set -euo pipefail

RULES_FILE="/etc/udev/rules.d/51-osmosis.rules"

echo "Installing OSmosis udev rules..."

sudo tee "$RULES_FILE" > /dev/null <<'RULES'
# OSmosis USB device rules — allow access without sudo
# Generated by scripts/setup-udev.sh

# Samsung (Download Mode + MTP)
SUBSYSTEM=="usb", ATTR{idVendor}=="04e8", MODE="0666", GROUP="plugdev"

# Google / Android (ADB + fastboot)
SUBSYSTEM=="usb", ATTR{idVendor}=="18d1", MODE="0666", GROUP="plugdev"

# LG
SUBSYSTEM=="usb", ATTR{idVendor}=="1004", MODE="0666", GROUP="plugdev"

# Xiaomi
SUBSYSTEM=="usb", ATTR{idVendor}=="2717", MODE="0666", GROUP="plugdev"

# Motorola
SUBSYSTEM=="usb", ATTR{idVendor}=="22b8", MODE="0666", GROUP="plugdev"

# HTC
SUBSYSTEM=="usb", ATTR{idVendor}=="0bb4", MODE="0666", GROUP="plugdev"

# OnePlus
SUBSYSTEM=="usb", ATTR{idVendor}=="2a70", MODE="0666", GROUP="plugdev"

# Huawei
SUBSYSTEM=="usb", ATTR{idVendor}=="12d1", MODE="0666", GROUP="plugdev"

# Fairphone
SUBSYSTEM=="usb", ATTR{idVendor}=="2ae5", MODE="0666", GROUP="plugdev"

# Sony
SUBSYSTEM=="usb", ATTR{idVendor}=="0fce", MODE="0666", GROUP="plugdev"

# Amazon (Fire devices)
SUBSYSTEM=="usb", ATTR{idVendor}=="1949", MODE="0666", GROUP="plugdev"

# Nothing
SUBSYSTEM=="usb", ATTR{idVendor}=="2b4c", MODE="0666", GROUP="plugdev"

# STMicroelectronics (ST-Link, STM32 DFU)
SUBSYSTEM=="usb", ATTR{idVendor}=="0483", MODE="0666", GROUP="plugdev"

# Espressif (ESP32, ESP8266)
SUBSYSTEM=="usb", ATTR{idVendor}=="303a", MODE="0666", GROUP="plugdev"

# Arduino
SUBSYSTEM=="usb", ATTR{idVendor}=="2341", MODE="0666", GROUP="plugdev"

# Adafruit
SUBSYSTEM=="usb", ATTR{idVendor}=="239a", MODE="0666", GROUP="plugdev"

# Raspberry Pi (RP2040)
SUBSYSTEM=="usb", ATTR{idVendor}=="2e8a", MODE="0666", GROUP="plugdev"

# FTDI (serial adapters)
SUBSYSTEM=="usb", ATTR{idVendor}=="0403", MODE="0666", GROUP="plugdev"

# Silicon Labs CP210x (serial adapters)
SUBSYSTEM=="usb", ATTR{idVendor}=="10c4", MODE="0666", GROUP="plugdev"

# CH340/CH341 (serial adapters)
SUBSYSTEM=="usb", ATTR{idVendor}=="1a86", MODE="0666", GROUP="plugdev"

# OpenMoko / HackRF / Great Scott Gadgets
SUBSYSTEM=="usb", ATTR{idVendor}=="1d50", MODE="0666", GROUP="plugdev"

# NXP (LPC DFU)
SUBSYSTEM=="usb", ATTR{idVendor}=="1fc9", MODE="0666", GROUP="plugdev"

# TI (calculators)
SUBSYSTEM=="usb", ATTR{idVendor}=="0451", MODE="0666", GROUP="plugdev"

# NumWorks (calculator DFU)
SUBSYSTEM=="usb", ATTR{idVendor}=="0483", ATTR{idProduct}=="a291", MODE="0666", GROUP="plugdev"
RULES

# Add user to plugdev group if not already
if ! groups "$USER" | grep -q plugdev 2>/dev/null; then
    if getent group plugdev >/dev/null 2>&1; then
        sudo usermod -aG plugdev "$USER"
        echo "Added $USER to plugdev group."
    fi
fi

# Reload udev rules
sudo udevadm control --reload-rules
sudo udevadm trigger

echo "Udev rules installed at $RULES_FILE"
echo "USB devices can now be accessed without sudo."
echo ""
echo "NOTE: If you just plugged in a device, unplug and replug it for the new rules to take effect."
