#!/usr/bin/env bash
# Set up nginx as a reverse proxy for OSmosis with self-signed TLS.
# Installs nginx if needed, generates a self-signed certificate,
# and configures the reverse proxy to Flask on localhost:5000.
#
# Usage:
#   bash scripts/setup-nginx.sh              # self-signed cert
#   bash scripts/setup-nginx.sh --letsencrypt example.com  # Let's Encrypt
#
# Safe to run multiple times (idempotent).
set -euo pipefail

OSMOSIS_PORT="${OSMOSIS_PORT:-5000}"
CERT_DIR="/etc/osmosis/tls"
NGINX_CONF="/etc/nginx/sites-available/osmosis"
NGINX_ENABLED="/etc/nginx/sites-enabled/osmosis"

USE_LETSENCRYPT=false
DOMAIN=""

while [[ $# -gt 0 ]]; do
    case "$1" in
        --letsencrypt)
            USE_LETSENCRYPT=true
            DOMAIN="${2:-}"
            if [[ -z "$DOMAIN" ]]; then
                echo "Error: --letsencrypt requires a domain name."
                echo "Usage: $0 --letsencrypt example.com"
                exit 1
            fi
            shift 2
            ;;
        *)
            echo "Unknown option: $1"
            exit 1
            ;;
    esac
done

# --- Install nginx if missing ---
if ! command -v nginx &>/dev/null; then
    echo "Installing nginx..."
    if command -v apt-get &>/dev/null; then
        sudo apt-get update -qq && sudo apt-get install -y -qq nginx
    elif command -v dnf &>/dev/null; then
        sudo dnf install -y nginx
    elif command -v pacman &>/dev/null; then
        sudo pacman -S --noconfirm nginx
    else
        echo "Error: Could not detect package manager. Install nginx manually."
        exit 1
    fi
fi

# --- Generate TLS certificate ---
if $USE_LETSENCRYPT; then
    echo "Setting up Let's Encrypt for $DOMAIN..."
    if ! command -v certbot &>/dev/null; then
        if command -v apt-get &>/dev/null; then
            sudo apt-get install -y -qq certbot python3-certbot-nginx
        elif command -v dnf &>/dev/null; then
            sudo dnf install -y certbot python3-certbot-nginx
        else
            echo "Error: Install certbot manually."
            exit 1
        fi
    fi

    # Write a minimal HTTP config first so certbot can verify
    sudo tee "$NGINX_CONF" > /dev/null <<HTTPEOF
server {
    listen 80;
    server_name $DOMAIN;

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://\$host\$request_uri;
    }
}
HTTPEOF

    sudo ln -sf "$NGINX_CONF" "$NGINX_ENABLED" 2>/dev/null || true
    sudo rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true
    sudo nginx -t && sudo systemctl reload nginx

    sudo certbot --nginx -d "$DOMAIN" --non-interactive --agree-tos \
        --register-unsafely-without-email --redirect

    echo "Let's Encrypt certificate installed for $DOMAIN."
    echo "Certbot auto-renewal is enabled by default."
else
    # Self-signed certificate
    sudo mkdir -p "$CERT_DIR"

    if [[ -f "$CERT_DIR/osmosis.crt" && -f "$CERT_DIR/osmosis.key" ]]; then
        echo "TLS certificate already exists at $CERT_DIR — skipping generation."
    else
        echo "Generating self-signed TLS certificate..."
        sudo openssl req -x509 -nodes -days 3650 \
            -newkey rsa:2048 \
            -keyout "$CERT_DIR/osmosis.key" \
            -out "$CERT_DIR/osmosis.crt" \
            -subj "/CN=osmosis-local/O=OSmosis/C=XX" \
            -addext "subjectAltName=DNS:localhost,IP:127.0.0.1" \
            2>/dev/null
        sudo chmod 600 "$CERT_DIR/osmosis.key"
        echo "Certificate generated at $CERT_DIR."
    fi

    # --- Write nginx config ---
    echo "Writing nginx config..."
    sudo tee "$NGINX_CONF" > /dev/null <<CONFEOF
# OSmosis reverse proxy — generated by scripts/setup-nginx.sh
# Do not edit manually; re-run the script to update.

server {
    listen 80;
    server_name _;
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate     $CERT_DIR/osmosis.crt;
    ssl_certificate_key $CERT_DIR/osmosis.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    # Security headers
    add_header X-Content-Type-Options nosniff always;
    add_header X-Frame-Options DENY always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy strict-origin-when-cross-origin always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    # Proxy to Flask
    location / {
        proxy_pass http://127.0.0.1:$OSMOSIS_PORT;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # WebSocket / SSE support
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 86400;

        # Allow large firmware uploads
        client_max_body_size 4G;
        proxy_request_buffering off;
    }
}
CONFEOF
fi

# --- Enable site ---
sudo ln -sf "$NGINX_CONF" "$NGINX_ENABLED" 2>/dev/null || true
sudo rm -f /etc/nginx/sites-enabled/default 2>/dev/null || true

# --- Test and reload ---
echo "Testing nginx configuration..."
sudo nginx -t

echo "Reloading nginx..."
sudo systemctl enable nginx
sudo systemctl reload nginx

echo ""
echo "OSmosis is now served via nginx:"
if $USE_LETSENCRYPT; then
    echo "  https://$DOMAIN"
else
    echo "  https://localhost  (self-signed certificate)"
fi
echo "  Flask backend:  http://127.0.0.1:$OSMOSIS_PORT (proxied, not exposed)"
